# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefas.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tarefas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtarefas.proto\x12\x07tarefas\"\x9e\x01\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x1f\n\x06status\x18\x04 \x01(\x0e\x32\x0f.tarefas.STATUS\x12\x13\n\x0b\x64\x61ta_limite\x18\x05 \x01(\t\x12\x13\n\x0bresponsavel\x18\x06 \x01(\t\x12\x0f\n\x07memoria\x18\x07 \x01(\x05\x12\x0b\n\x03\x63pu\x18\x08 \x01(\x05\"\x99\x01\n\rRequest_Criar\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x1f\n\x06status\x18\x03 \x01(\x0e\x32\x0f.tarefas.STATUS\x12\x13\n\x0b\x64\x61ta_limite\x18\x04 \x01(\t\x12\x13\n\x0bresponsavel\x18\x05 \x01(\t\x12\x0f\n\x07memoria\x18\x06 \x01(\x05\x12\x0b\n\x03\x63pu\x18\x07 \x01(\x05\"\x10\n\x0eRequest_Listar\")\n\x05Lista\x12 \n\x07tarefas\x18\x01 \x03(\x0b\x32\x0f.tarefas.Tarefa\"\xa9\x01\n\x11Request_Atualizar\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x1f\n\x06status\x18\x04 \x01(\x0e\x32\x0f.tarefas.STATUS\x12\x13\n\x0b\x64\x61ta_limite\x18\x05 \x01(\t\x12\x13\n\x0bresponsavel\x18\x06 \x01(\t\x12\x0f\n\x07memoria\x18\x07 \x01(\x05\x12\x0b\n\x03\x63pu\x18\x08 \x01(\x05\"\x1d\n\x0fRequest_Deletar\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x06\x44\x65lete\x12\x10\n\x08\x64\x65letado\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t*9\n\x06STATUS\x12\x0e\n\nAGUARDANDO\x10\x00\x12\x0f\n\x0bPROCESSANDO\x10\x01\x12\x0e\n\nFINALIZADA\x10\x02\x32\xec\x01\n\rTarefaService\x12\x32\n\x05\x43riar\x12\x16.tarefas.Request_Criar\x1a\x0f.tarefas.Tarefa\"\x00\x12\x33\n\x06Listar\x12\x17.tarefas.Request_Listar\x1a\x0e.tarefas.Lista\"\x00\x12:\n\tAtualizar\x12\x1a.tarefas.Request_Atualizar\x1a\x0f.tarefas.Tarefa\"\x00\x12\x36\n\x07\x44\x65letar\x12\x18.tarefas.Request_Deletar\x1a\x0f.tarefas.Delete\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=653
  _globals['_STATUS']._serialized_end=710
  _globals['_TAREFA']._serialized_start=27
  _globals['_TAREFA']._serialized_end=185
  _globals['_REQUEST_CRIAR']._serialized_start=188
  _globals['_REQUEST_CRIAR']._serialized_end=341
  _globals['_REQUEST_LISTAR']._serialized_start=343
  _globals['_REQUEST_LISTAR']._serialized_end=359
  _globals['_LISTA']._serialized_start=361
  _globals['_LISTA']._serialized_end=402
  _globals['_REQUEST_ATUALIZAR']._serialized_start=405
  _globals['_REQUEST_ATUALIZAR']._serialized_end=574
  _globals['_REQUEST_DELETAR']._serialized_start=576
  _globals['_REQUEST_DELETAR']._serialized_end=605
  _globals['_DELETE']._serialized_start=607
  _globals['_DELETE']._serialized_end=651
  _globals['_TAREFASERVICE']._serialized_start=713
  _globals['_TAREFASERVICE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
