# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tarefas_pb2 as tarefas__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tarefas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TarefaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Criar = channel.unary_unary(
                '/tarefas.TarefaService/Criar',
                request_serializer=tarefas__pb2.Request_Criar.SerializeToString,
                response_deserializer=tarefas__pb2.Tarefa.FromString,
                _registered_method=True)
        self.Listar = channel.unary_unary(
                '/tarefas.TarefaService/Listar',
                request_serializer=tarefas__pb2.Request_Listar.SerializeToString,
                response_deserializer=tarefas__pb2.Lista.FromString,
                _registered_method=True)
        self.Atualizar = channel.unary_unary(
                '/tarefas.TarefaService/Atualizar',
                request_serializer=tarefas__pb2.Request_Atualizar.SerializeToString,
                response_deserializer=tarefas__pb2.Tarefa.FromString,
                _registered_method=True)
        self.Deletar = channel.unary_unary(
                '/tarefas.TarefaService/Deletar',
                request_serializer=tarefas__pb2.Request_Deletar.SerializeToString,
                response_deserializer=tarefas__pb2.Delete.FromString,
                _registered_method=True)


class TarefaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Criar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Atualizar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deletar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TarefaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Criar': grpc.unary_unary_rpc_method_handler(
                    servicer.Criar,
                    request_deserializer=tarefas__pb2.Request_Criar.FromString,
                    response_serializer=tarefas__pb2.Tarefa.SerializeToString,
            ),
            'Listar': grpc.unary_unary_rpc_method_handler(
                    servicer.Listar,
                    request_deserializer=tarefas__pb2.Request_Listar.FromString,
                    response_serializer=tarefas__pb2.Lista.SerializeToString,
            ),
            'Atualizar': grpc.unary_unary_rpc_method_handler(
                    servicer.Atualizar,
                    request_deserializer=tarefas__pb2.Request_Atualizar.FromString,
                    response_serializer=tarefas__pb2.Tarefa.SerializeToString,
            ),
            'Deletar': grpc.unary_unary_rpc_method_handler(
                    servicer.Deletar,
                    request_deserializer=tarefas__pb2.Request_Deletar.FromString,
                    response_serializer=tarefas__pb2.Delete.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarefas.TarefaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarefas.TarefaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TarefaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Criar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.TarefaService/Criar',
            tarefas__pb2.Request_Criar.SerializeToString,
            tarefas__pb2.Tarefa.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Listar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.TarefaService/Listar',
            tarefas__pb2.Request_Listar.SerializeToString,
            tarefas__pb2.Lista.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Atualizar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.TarefaService/Atualizar',
            tarefas__pb2.Request_Atualizar.SerializeToString,
            tarefas__pb2.Tarefa.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deletar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.TarefaService/Deletar',
            tarefas__pb2.Request_Deletar.SerializeToString,
            tarefas__pb2.Delete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
